option(
    'static',
    type: 'boolean',
    value: true,
    description: 'Whether link static or shared libraries against an executable'
)

option(
    'force_32bit',
    type: 'boolean',
    value: false,
    description: 'Force compiler to build in 32-bit mode instead'
)

option(
    'workdir_current',
    type: 'boolean',
    value: false,
    description: 'Keep Current Working Directory on startup'
)

option(
    'gl_backend',
    type: 'combo',
    choices: ['gl', 'gles'],
    value: 'gl',
    description: 'Whether use OpenGL or OpenGL ES'
)

option(
    'require_nanosleep',
    type: 'combo',
    choices: ['auto', 'true', 'false'],
    value: 'auto',
    description: 'Whether use nanosleep for ticking framerate. Affects to framerate steadiness on Windows.'
)

option(
    'appimagetool',
    type: 'string',
    value: '',
    description: 'Path to AppImageTool binary. Providing will pack to AppImage file on install'
)

# mkxp-z modules options
option(
    'cjk_font',
    type: 'boolean',
    value: false,
    description: 'Use WenQuanYi Micro Hei as the fallback font'
)

option(
    'fluidsynth',
    type: 'boolean',
    value: true,
    description: 'Enable FluidSynth (MIDI support)'
)

option(
    'miniffi',
    type: 'boolean',
    value: true,
    description: 'Enable MiniFFI Ruby bindings (Win32API)'
)

option(
    'https',
    type: 'boolean',
    value: true,
    description: 'Enable HTTPLite Ruby bindings (HTTPS support, Requires OpenSSL)'
)

option(
    'cxx11_experimental',
    type: 'boolean',
    value: false,
    description: 'Toggles between using ghc/filesystem or C++11 <experimental/filesystem>'
)

option(
    'simple_smooth_scaling',
    type: 'boolean',
    value: false,
    description: 'Excludes more graphics smooth scaling variants to only Bilinear, for older GPUs support'
)

# Steamworks and Steamshim options
option(
    'steamworks_sdk',
    type: 'string',
    value: '',
    description: 'Path to Steamworks SDK. Providing will enable Steam features and bindings'
)

option(
    'steam_appid',
    type: 'string',
    value: '',
    description: 'Steam AppID value. Set this to use SteamAPI_RestartAppIfNecessary'
)

option(
    'steamshim_debug',
    type: 'boolean',
    value: false,
    description: 'Whether to show Steamshim debug output console'
)

# Ruby library dependency options
option(
    'mri_version',
    type: 'string',
    value: '3.1',
    description: 'Version of Ruby library to link with'
)

option(
    'mri_includes',
    type: 'string',
    value: '',
    description: 'Manual include path to Ruby headers'
)

option(
    'mri_libname',
    type: 'string',
    value: '',
    description: 'Manual library name of Ruby library'
)

option(
    'mri_libpath',
    type: 'string',
    value: '',
    description: 'Manual library path to Ruby library'
)
